name: Configuration Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate starship.toml
      run: |
        sudo apt-get install -y starship
        starship explain --config ../../../../C:/Users/butir/dotfiles/starship.toml

    - name: Validate PowerShell profile
      run: |
        pwsh -Command "Invoke-Expression -Command { . ./Microsoft.PowerShell_profile.ps1 }"