name: Configuration Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install starship
      run: |
        curl -fsSL https://starship.rs/install.sh | sh -s -- -y

    - name: Validate starship.toml
      run: |
        ~/.cargo/bin/starship explain --config ./starship.toml

    - name: Validate PowerShell profile
      run: |
        pwsh -Command "Invoke-Expression -Command { . ./Microsoft.PowerShell_profile.ps1 }"