name: Configuration Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install starship
      run: |
        curl -fsSL https://starship.rs/install.sh | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # Fixed deprecated add-path command

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Validate starship.toml
      run: |
        starship explain --config ./starship.toml

    - name: Validate PowerShell profile
      run: |
        pwsh -NoProfile -Command "Test-Path -Path ./Microsoft.PowerShell_profile.ps1 -PathType Leaf"
        pwsh -NoProfile -Command ". ./Microsoft.PowerShell_profile.ps1"