name: Render Starship Prompt

on:
  push:  # Run on every push

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install Starship
        run: |
          # Install Starship using sh (to avoid non-POSIX issues)
          curl -fsSL https://starship.rs/install.sh | sh -s -- -y
          # Make sure Starship is in the PATH.
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install required packages (aha & chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y aha chromium-browser

      - name: Generate Starship prompt text
        env:
          STARSHIP_CONFIG: ${{ github.workspace }}/starship.toml
        run: |
          # Render the Starship prompt (with ANSI colors and Nerd Font icons)
          starship prompt > prompt.txt
          cat prompt.txt

      - name: Convert ANSI output to HTML snippet
        run: |
          # Convert the ANSI codes in prompt.txt to an HTML snippet using aha.
          cat prompt.txt | aha --no-header > prompt_snippet.html

      - name: Create full HTML file for screenshot
        run: |
          # Wrap the HTML snippet in a complete HTML file with custom CSS.
          cat << 'EOF' > prompt.html
          <html>
          <head>
            <meta charset="utf-8">
            <style>
              /* Customize these styles as needed.
                 The fonts specified below support Nerd Font icons. */
              body {
                background-color: #282c34;
                color: #abb2bf;
                font-family: 'MesloLGS NF', 'Fira Code', monospace;
                font-size: 16px;
                line-height: 1.5;
                padding: 20px;
                white-space: pre;
              }
            </style>
          </head>
          <body>
          EOF
          cat prompt_snippet.html >> prompt.html
          echo "</body></html>" >> prompt.html

      - name: Capture screenshot of rendered prompt
        run: |
          # Use Chromium in headless mode to take a screenshot of prompt.html.
          chromium-browser --headless --disable-gpu \
            --screenshot=starship_prompt.png \
            --window-size=1200,200 \
            "file://$GITHUB_WORKSPACE/prompt.html"

      - name: Update README with screenshot
        run: |
          # Replace the screenshot block between marker comments if it exists,
          # or append the block otherwise.
          if grep -q '<!-- starship prompt screenshot start -->' README.md; then
            awk '
              /<!-- starship prompt screenshot start -->/ {
                print;
                print "![Starship Prompt](starship_prompt.png)";
                inBlock = 1;
                next;
              }
              /<!-- starship prompt screenshot end -->/ {
                inBlock = 0;
              }
              { if (!inBlock) print }
            ' README.md > tmp_README.md && mv tmp_README.md README.md
          else
            {
              echo "";
              echo "<!-- starship prompt screenshot start -->";
              echo "![Starship Prompt](starship_prompt.png)";
              echo "<!-- starship prompt screenshot end -->";
            } >> README.md
          fi

      - name: Commit and push updated README and screenshot
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add README.md starship_prompt.png
          git commit -m "Update starship prompt screenshot" || echo "No changes to commit"
          git push
