name: Render Starship Prompt

on:
  push:  # Run on every push

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install Starship
        run: |
          # Install Starship using sh to avoid non-POSIX bash issues.
          curl -fsSL https://starship.rs/install.sh | sh -s -- -y
          # Ensure Starship is on the PATH.
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install required packages (aha & chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y aha chromium-browser

      - name: Generate screenshots for language directories
        run: |
          for lang in java python php; do
            echo "Processing language: $lang"
            mkdir -p "${lang}_project"
            if [ "$lang" = "java" ]; then
              echo "public class HelloWorld {}" > "${lang}_project/HelloWorld.java"
            elif [ "$lang" = "python" ]; then
              echo "print('Hello, world')" > "${lang}_project/app.py"
            elif [ "$lang" = "php" ]; then
              echo "<?php echo 'Hello, world'; ?>" > "${lang}_project/index.php"
            fi

            # Run Starship in the project directory so that its prompt reflects that context.
            (cd "${lang}_project" && starship prompt > "../prompt_${lang}.txt")

            # Convert the ANSI-colored prompt to an HTML snippet.
            cat "prompt_${lang}.txt" | aha --no-header > "prompt_snippet_${lang}.html"

            # Create a full HTML file wrapping the snippet.
            # The CSS below uses JetBrains Mono Nerd Font.
            cat << 'EOF' > "prompt_${lang}.html"
            <html>
            <head>
              <meta charset="utf-8">
              <style>
                body {
                  background-color: #282c34;
                  color: #abb2bf;
                  font-family: 'JetBrainsMono Nerd Font', 'JetBrains Mono', monospace;
                  font-size: 16px;
                  line-height: 1.5;
                  padding: 20px;
                  white-space: pre;
                }
              </style>
            </head>
            <body>
            EOF
            cat "prompt_snippet_${lang}.html" >> "prompt_${lang}.html"
            echo "</body></html>" >> "prompt_${lang}.html"

            # Capture a screenshot with Chromium in headless mode.
            chromium-browser --headless --disable-gpu \
              --screenshot="starship_prompt_${lang}.png" \
              --window-size=1200,200 \
              "file://$PWD/prompt_${lang}.html"
          done

      - name: Update README with screenshots
        run: |
          if grep -q '<!-- starship prompt screenshot start -->' README.md; then
            awk '
              /<!-- starship prompt screenshot start -->/ {
                print;
                print "![Starship Prompt (Java)](starship_prompt_java.png)";
                print "![Starship Prompt (Python)](starship_prompt_python.png)";
                print "![Starship Prompt (PHP)](starship_prompt_php.png)";
                inBlock = 1;
                next;
              }
              /<!-- starship prompt screenshot end -->/ {
                inBlock = 0;
              }
              { if (!inBlock) print }
            ' README.md > tmp_README.md && mv tmp_README.md README.md
          else
            {
              echo "";
              echo "<!-- starship prompt screenshot start -->";
              echo "![Starship Prompt (Java)](starship_prompt_java.png)";
              echo "![Starship Prompt (Python)](starship_prompt_python.png)";
              echo "![Starship Prompt (PHP)](starship_prompt_php.png)";
              echo "<!-- starship prompt screenshot end -->";
            } >> README.md
          fi

      - name: Commit and push updated README and screenshots
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add README.md starship_prompt_java.png starship_prompt_python.png starship_prompt_php.png
          git commit -m "Update starship prompt screenshots" || echo "No changes to commit"
          git push
