name: Render Starship Prompt

on:
  push:  # Run on every push

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Starship
        run: |
          # Use 'sh' instead of 'bash' to avoid non-POSIX issues.
          curl -fsSL https://starship.rs/install.sh | sh -s -- -y
          # Make sure the Starship binary is available in the PATH.
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install required packages (aha & chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y aha chromium-browser

      - name: Generate Starship prompt text
        env:
          STARSHIP_CONFIG: ${{ github.workspace }}/starship.toml
        run: |
          # Generate ANSI-colored prompt output with Nerd Font icons.
          starship prompt > prompt.txt
          cat prompt.txt

      - name: Convert ANSI output to HTML snippet
        run: |
          # Convert ANSI escape sequences to an HTML snippet.
          cat prompt.txt | aha --no-header > prompt_snippet.html

      - name: Create full HTML file for screenshot
        run: |
          # Wrap the HTML snippet with our own HTML and custom CSS.
          cat << 'EOF' > prompt.html
          <html>
          <head>
            <meta charset="utf-8">
            <style>
              /* Adjust these styles as needed. The font-family below uses
                 popular Nerd Font choices. */
              body {
                background-color: #282c34;
                color: #abb2bf;
                font-family: 'MesloLGS NF', 'Fira Code', monospace;
                font-size: 16px;
                line-height: 1.5;
                padding: 20px;
                white-space: pre;
              }
            </style>
          </head>
          <body>
          EOF
          cat prompt_snippet.html >> prompt.html
          echo "</body></html>" >> prompt.html

      - name: Capture screenshot of rendered prompt
        run: |
          # Use Chromium headless to take a screenshot of the HTML page.
          chromium-browser --headless --disable-gpu \
            --screenshot=starship_prompt.png \
            --window-size=1200,200 \
            "file://$GITHUB_WORKSPACE/prompt.html"

      - name: Update README with screenshot
        run: |
          # Look for marker comments in README.md and update the screenshot image link.
          if grep -q '<!-- starship prompt screenshot start -->' README.md; then
            sed -i '/<!-- starship prompt screenshot start -->/,/<!-- starship prompt screenshot end -->/c\<!-- starship prompt screenshot start -->\n![Starship Prompt](starship_prompt.png)\n<!-- starship prompt screenshot end -->' README.md
